const Photo =[
    {
        id:1,
        image:"./Img/blog-1.jpg",
        category:"FITNESS"
    },
    {
        id:2,
        image:"./Img/blog-2.jpg",
        category:"EVENT"
    },
    {
        id:3,
        image:"./Img/blog-3.jpg",
        category:"COACHING"
    },
    {
        id:4,
        image:"./Img/blog-4.jpg",
        category:"FITNESS"
    },
    {
        id:5,
        image:"./Img/blog-5.jpg",
        category:"EVENT"
    },
    {
        id:6,
        image:"./Img/blog-6.jpg",
        category:"COACHING"
    },{
        id:7,
        image:"./Img/blog-7.jpg",
        category:"FITNESS"
    },
    {
        id:8,
        image:"./Img/blog-8.jpg",
        category:"EVENT"
    },
    {
        id:9,
        image:"./Img/blog-9.jpg",
        category:"COACHING"
    },
]